INSERT INTO PRODUCT (PRODUCTID, DESCRIPTION, PRICE, CURRENCYCODE) VALUES ('product1', 'descr1', 25.0, 'EUR');
INSERT INTO PRODUCT (PRODUCTID, DESCRIPTION, PRICE, CURRENCYCODE) VALUES ('product2', 'descr2', 25.0, 'USD');
INSERT INTO PRODUCT (PRODUCTID, DESCRIPTION, PRICE, CURRENCYCODE) VALUES ('product3', 'descr3', 25.0, 'EUR');